### ISSUE TITLE
Make test fails on strawberry perl

### ISSUE THREAD

**Issue by ElliotPsyIT** [vti/dancer-template-caml#1]
Sorry, I'm a relatively new perl programmer.  This issue I'm submitting may have simple answer where I have done something wrong or omitting doing something.  And, I am brand new to git as well.  So I may be sending this question to the wrong place.  If so, my apologies.

I've pulled your excellent looking Dancer blog app called 'twist' that requires tempate::caml.  So I attempted to install dancer::template::caml using strawberry perl's (v. 5.12) cpan shell.  Make test reports 1/3 test failed at t/app.t line 22.  The output show Failed test 'response content looks good for GET /', and then prints out html page for a 500 error. The t/main.t test(s) run fine.  I might be able to force the install, but didn't want to do that without understanding the reason for the test error.  Could I trouble you to assist?

**Comment by vti** [comment]
Thanks for the report. I've just tried installing Dancer::Template::Caml on Windows with Strawberry perl and got the same error as you. But I have no idea why :( I couldn't run Dancer's tests too. Maybe there is some issue with sockets or firewall, or simply the test is wrong. Try force installing and let me know the results. Thanks.

**Comment by ElliotPsyIT** [comment]
I've force installed Dancer::Template::Caml.  I started Dancer, but cannot
get twist to start.  I'm a bit embarrassed to send the problem, being a
newbie trying to understand Dancer and your excellent work.  But here goes.
 Dancer's run-time error shows the failure in Dancer/Template/Caml.pm at
line 40.  The specific error is 'Can't find \Index.caml'.  The Index.caml
file is in the /views directory as expected. Examining Caml.pm line 40
shows the error occurs calling the render_file method on $_engine. I should
mention that I started Dancer with the default server and not Plack (just
trying to limit my learning curve), which I'm mentioning since the engine
object is involved in the error.

Any assistance would be greatly appreciated!

Elliot

On Sun, Jan 22, 2012 at 4:11 AM, Viacheslav Tykhanovskyi <
reply@reply.github.com

> wrote:
> 
> Thanks for the report. I've just tried installing Dancer::Template::Caml
> on Windows with Strawberry perl and got the same error as you. But I have
> no idea why :( I couldn't run Dancer's tests too. Maybe there is some issue
> with sockets or firewall, or simply the test is wrong. Try force installing
> and let me know the results. Thanks.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vti/dancer-template-caml/issues/1#issuecomment-3602128

## 

Elliot M. Fielstein, Ph.D.

**Comment by vti** [comment]
Ok. I guess I fixed the issue. It was due to non portable path manipulations. Try installing Dancer::Template::Caml from github. If you use Strawberry perl you can do this from terminal:

```
cpan http://github.com/vti/dancer-template-caml/zipball/master
```

**Comment by ElliotPsyIT** [comment]
Got an error with the cpan installation from github when using the command
and link you suggested.  Cpan seems to be trying to create a subdir using
part of the github URL - "mkdir
C:\Strawberry\cpan\sources\authors\id\h\h\h\ht\http:\: Invalid
argument; The filename, ddirectory name, or vollume label syntax is
incorrect at C:\strawberry\perl\lib/CPAN/FTP.pm line 513\cJ".

I googled for other ways to install a perl module from github using cpan
shell, to see if I could try something else, but didn't see a direct
comment on this.

On Tue, Jan 24, 2012 at 4:37 AM, Viacheslav Tykhanovskyi <
reply@reply.github.com

> wrote:
> 
> Ok. I guess I fixed the issue. It was due to non portable path
> manipulations. Try installing Dancer::Template::Caml from github. If you
> use Strawberry perl you can do this from terminal:
> 
>    cpan http://github.com/vti/dancer-template-caml/zipball/master
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vti/dancer-template-caml/issues/1#issuecomment-3630381

## 

Elliot M. Fielstein, Ph.D.

**Comment by vti** [comment]
Sorry about that, I forgot that installing from URL works in cpanminus, not cpan. Try this:

```
cpan App::cpanminus
```

and then (notice the 'm' letter after cpan)

```
cpanm http://github.com/vti/dancer-template-caml/zipball/master
```

**Comment by ElliotPsyIT** [comment]
Well, good news and bad.  App::cpanminus installed without a problem.

But using cpanm to install the new version of Dancer::Template::Caml from
Github failed.  Here's the output:

C:>cpanm http://github.com/vti/dancer-template-caml/zipball/master
--> Working on http://github.com/vti/dancer-template-caml/zipball/master
Fetching http://github.com/vti/dancer-template-caml/zipball/master ... OK
Invalid header block at offset unknown at
/loader/0x9deebc/App/cpanminus/script
pm line 1851
Invalid header block at offset unknown at
/loader/0x9deebc/App/cpanminus/script
pm line 1851
Invalid header block at offset unknown at
/loader/0x9deebc/App/cpanminus/script
pm line 1851
Invalid header block at offset unknown at
/loader/0x9deebc/App/cpanminus/script
pm line 1851
Invalid header block at offset unknown at
/loader/0x9deebc/App/cpanminus/script
pm line 1851
Invalid header block at offset unknown at
/loader/0x9deebc/App/cpanminus/script
pm line 1851
Invalid header block at offset unknown at
/loader/0x9deebc/App/cpanminus/script
pm line 1851
Invalid header block at offset unknown at
/loader/0x9deebc/App/cpanminus/script
pm line 1851
Invalid header block at offset unknown at
/loader/0x9deebc/App/cpanminus/script
pm line 1851
No data could be read from file at /loader/0x9deebc/App/cpanminus/script.pmlin
 1851
Can't call method "list_files" on an undefined value at
/loader/0x9deebc/App/cp
nminus/script.pm line 1852.

On Tue, Jan 24, 2012 at 9:00 AM, Viacheslav Tykhanovskyi <
reply@reply.github.com

> wrote:
> 
> Sorry about that, I forgot that installing from URL works in cpanminus,
> not cpan. Try this:
> 
>    cpan App::cpanminus
> 
> and then (notice the 'm' letter after cpan)
> 
>   cpanm http://github.com/vti/dancer-template-caml/zipball/master
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vti/dancer-template-caml/issues/1#issuecomment-3633582

## 

Elliot M. Fielstein, Ph.D.

**Comment by vti** [comment]
Looks like a cpanm bug. Anyway, to reduce your pain I've released Dancer::Template::Caml to CPAN today, try installing it as a normal module (version 0.10, it's not immediately available, maybe in half an hour).

**Comment by ElliotPsyIT** [comment]
Good news is that I installed the updated module, but it took my a few
tries (caution: newbie).

I tried to use cpanm to install Dancer::Template::Caml, but it failed
during an intermediary process - something like failed to build
ExtMakeMaker, sorry but I can't remember precisely.  Then, I went back to
using cpan install and simple got the message that the module was
installed, but it was the last version and not the new one.  I quickly
googled on updating a module's version and didn't see anything obvious, but
I say a way to intall using the tar.gz - so I install
VTI/Dancer-Template-Caml.0.10.tar.gz, and it worked.  I was a little
worried though, because the install first went through installing a set of
dependencies with lengthy tests, but eventually completed successfully.

I started up Dancer, and Twist loaded and displayed successfully!

I wanted to add that I have been reviewing a number of perl web app
frameworks, a number of perl authors' approaches to OO in the context of
web development, and looked at various perl testing approaches, and I must
say I am most impressed with your work.  So I'm studying your code design
and testing style through Twist (I started with Bootylicious, but I moved
to away from Mojolicious to Dancer because of Mojo's steep learning curve -
plus I read your critique:) ), and hope to try and extend Twist to include
some of the addition features you have in Bootylicious, just as an
exercise.  I'm a newbie OO programmer, semi-experienced perl programmer,
and relatively newbie web app developer (actually a psychologist by
training moving into informatics and analytics).

I greatly appeciate your help, and your open source contributions.  Thank
you.

Best regards,

Elliot Fielstein

On Wed, Jan 25, 2012 at 2:34 AM, Viacheslav Tykhanovskyi <
reply@reply.github.com

> wrote:
> 
> Looks like a cpanm bug. Anyway, to reduce your pain I've released
> Dancer::Template::Caml to CPAN today, try installing it as a normal module
> (version 0.10, it's not immediately available, maybe in half an hour).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vti/dancer-template-caml/issues/1#issuecomment-3647404

## 

Elliot M. Fielstein, Ph.D.

**Comment by vti** [comment]
Heh, I'm glad this issue is finally resolved. I guess we can close it :) As for cpan usually you have to wait until the module is mirrored across the world and is available on the server you are installing from. So I guess it wasn't there when you tried it.

If you have any questions about clean code, OOP, design patterns, TDD feel free to write directly on my email. Always glad to help!

**Comment by ElliotPsyIT** [comment]
Yes, it's resolved and so the issue can be closed.

Your offer to answer questions is very generous, thank you!  I may just
take you up on it, mindful to not usurp too much of your time.

Very good of you.  Take care.

On Wed, Jan 25, 2012 at 3:36 PM, Viacheslav Tykhanovskyi <
reply@reply.github.com

> wrote:
> 
> Heh, I'm glad this issue is finally resolved. I guess we can close it :)
> As for cpan usually you have to wait until the module is mirrored across
> the world and is available on the server you are installing from. So I
> guess it wasn't there when you tried it.
> 
> If you have any questions about clean code, OOP, design patterns, TDD feel
> free to write directly on my email. Always glad to help!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vti/dancer-template-caml/issues/1#issuecomment-3659560

## 

Elliot M. Fielstein, Ph.D.
